#!/bin/sh
set -eu

workspace="${CI_WORKSPACE:-$PWD}"
config_dir="$workspace/Config"
config_file="$config_dir/AISecrets.xcconfig"

mkdir -p "$config_dir"

escape_for_xcconfig() {
    # Avoid accidental comment parsing for URLs (//) in xcconfig.
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g'
}

append_if_set() {
    var_name="$1"
    key_name="$2"
    eval "raw_value=\${$var_name-}"

    if [ -n "${raw_value}" ]; then
        escaped_value="$(escape_for_xcconfig "$raw_value")"
        printf '%s = %s\n' "$key_name" "$escaped_value" >> "$config_file"
    fi
}

cat > "$config_file" <<EOC
// Generated by ci_scripts/ci_post_clone.sh in Xcode Cloud.
// Do not commit this file.
// Only non-empty environment variables are written so Base.xcconfig defaults are preserved.
EOC

append_if_set AI_API_ENDPOINT AI_API_ENDPOINT
append_if_set AI_API_KEY AI_API_KEY
append_if_set AI_MODEL AI_MODEL

append_if_set NOTION_CLIENT_ID NOTION_CLIENT_ID
append_if_set NOTION_REDIRECT_URI NOTION_REDIRECT_URI

append_if_set SECURE_SERVER_BASE_URL SECURE_SERVER_BASE_URL
append_if_set SECURE_SERVER_CLIENT_ID SECURE_SERVER_CLIENT_ID
append_if_set SECURE_SERVER_CLIENT_SECRET SECURE_SERVER_CLIENT_SECRET
append_if_set SECURE_SERVER_REQUIRE_TLS SECURE_SERVER_REQUIRE_TLS
append_if_set SECURE_SERVER_METRICS_TOKEN SECURE_SERVER_METRICS_TOKEN

append_if_set ADMOB_BANNER_AD_UNIT_ID ADMOB_BANNER_AD_UNIT_ID
append_if_set ADMOB_REWARDED_INTERSTITIAL_AD_UNIT_ID ADMOB_REWARDED_INTERSTITIAL_AD_UNIT_ID
append_if_set ADMOB_INTERSTITIAL_AD_UNIT_ID ADMOB_INTERSTITIAL_AD_UNIT_ID

append_if_set ADS_SWIFT_FLAGS ADS_SWIFT_FLAGS

printf 'Generated %s\n' "$config_file"
