#!/bin/bash

# AI Summary 动态本地化测试脚本
# 用于验证提示词模板是否正确响应语言切换

echo "======================================"
echo "AI Summary 动态本地化测试"
echo "======================================"
echo ""

echo "📋 测试步骤："
echo ""
echo "1. 启动应用"
echo "   运行: ./scripts/run.sh"
echo ""
echo "2. 导入一本测试书籍"
echo "   - 点击 '导入书籍' 按钮"
echo "   - 选择 Test Files/test.epub 或其他 ePub 文件"
echo ""
echo "3. 切换到中文"
echo "   - 进入 设置 (Settings)"
echo "   - 点击 语言 (Language)"
echo "   - 选择 '中文'"
echo ""
echo "4. 生成 AI 摘要（中文）"
echo "   - 返回书架，点击刚导入的书籍"
echo "   - 点击 'AI 导读摘要' 或生成摘要按钮"
echo "   - 查看 Xcode 控制台日志，确认："
echo "     ✓ 日志显示：当前应用语言设置 = zh-Hans"
echo "     ✓ 提示词 (Prompt) 中包含中文指令"
echo "     ✓ 例如：'请为以下书籍生成一份导读摘要'"
echo ""
echo "5. 切换到英文"
echo "   - 进入 设置 (Settings)"
echo "   - 点击 语言 (Language)"
echo "   - 选择 'English'"
echo ""
echo "6. 重新生成 AI 摘要（英文）"
echo "   - 返回书架，点击同一本书"
echo "   - 再次生成摘要（可能需要先清除缓存）"
echo "   - 查看 Xcode 控制台日志，确认："
echo "     ✓ 日志显示：当前应用语言设置 = en"
echo "     ✓ 提示词 (Prompt) 中包含英文指令"
echo "     ✓ 例如：'Please generate a reading guide summary'"
echo ""
echo "7. 测试其他语言"
echo "   - 重复步骤 3-6，测试日语 (ja) 和韩语 (ko)"
echo ""

echo "======================================"
echo "🔍 查看日志的方法："
echo "======================================"
echo ""
echo "在 Xcode 控制台中搜索以下关键词："
echo "  • '当前应用语言设置'"
echo "  • '提示词 (Prompt) 开始'"
echo "  • 'buildSummaryPrompt'"
echo "  • 'buildChapterSummaryPrompt'"
echo ""

echo "======================================"
echo "✅ 预期结果："
echo "======================================"
echo ""
echo "1. 切换语言后，提示词模板立即使用新语言"
echo "2. 不需要重启应用"
echo "3. 日志中清晰显示当前使用的语言"
echo "4. 每种语言的提示词符合该语言的表达习惯"
echo ""

echo "======================================"
echo "❌ 如果测试失败："
echo "======================================"
echo ""
echo "请检查："
echo "  • LocalizationHelper.swift 是否已添加到项目中"
echo "  • AISummaryService.swift 是否使用 LocalizationHelper"
echo "  • 对应语言的 Localizable.strings 文件是否包含所有必需的键值"
echo "  • AppSettings.shared.language 是否正确更新"
echo ""

echo "======================================"
echo "📝 相关文件："
echo "======================================"
echo ""
echo "  • Isla Reader/Utils/LocalizationHelper.swift"
echo "  • Isla Reader/Utils/AISummaryService.swift"
echo "  • Isla Reader/en.lproj/Localizable.strings"
echo "  • Isla Reader/zh-Hans.lproj/Localizable.strings"
echo "  • Isla Reader/ja.lproj/Localizable.strings"
echo "  • Isla Reader/ko.lproj/Localizable.strings"
echo ""

echo "======================================"
echo "准备开始测试？ 运行应用："
echo "  ./scripts/run.sh"
echo "======================================"

